packages:
  - packages/**/*
  - examples/*

catalog:
  "@types/node": 22.19.0
  "@biomejs/biome": ^2.2.7
  nitro: 3.0.1-alpha.1
  typescript: ^5.9.3
  vitest: ^3.2.4
  zod: ^4.1.11
  

savePrefix: ""

